<h2>So, what's in an Anchor theme?</h2>
<p>In order to work correctly, Anchor requires a certain set of files:</p>

<dl>
	<dt id="about">about.txt</dt>
	    <dd>This file contains the metadata for your theme. As of version 0.5, however, only the "title" field is used.</dd>
	<dt id="posts">posts.php</dt>
	    <dd>This is the equivalent of Wordpress' <code>index.php</code>. This file handles the homepage's content.</dd>
	<dt id="article">article.php</dt>
	    <dd>This file handles a single post page.</dd>
	<dt id="page">page.php</dt>
	    <dd>This file handles a page generated by the CMS (e.g an About page).</dd>
	<dt id="search">search.php</dt>
	    <dd>This file handles the search results.</dd>
	<dt id="404">404.php</dt>
	    <dd>If a user navigates to a missing page, this file will be called.</dd>
</dl>

<p>There is also a <b>required</b> <code>includes</code> folder, which must contain the following files:</p>

<dl>
	<dt>header.php</dt>
	    <dd>This will be called at the beginning of every page. It's recommended that you put your code from the <code>&lt;head&gt;</code> in here.</dd>
	<dt>footer.php</dt>
	    <dd>And this will be called at the end of every page.</dd>
    <dt>comment_form.php</dt>
        <dd>This file holds both the comment output (list of comments) and the comment form.</dd>
</dl>

<p>Although not required, there are a number of extra files you can add that will be automatically recognised by Anchor:</p>
<dl>
    <dt id="functions">functions.php</dt>
        <dd>If you need to add any extra functionality to Anchor, you can write custom PHP functions here. Although not required, it is highly recommended you <a href="/docs/functions#namespacing">namespace your functions</a>.</dd>
</dl>

<p>Any other files can be added to your theme, but they will not be automatically picked up by Anchor, so you will have to manually include them.</p>